### ISSUE TITLE
Remove ExternalData support

### ISSUE THREAD

**Issue by doom369** [blynkkk/clickhouse4j#78]

**Comment by IgnatBeresnev** [comment]
Why did you decide to remove external data support? That's one of the features that's used in my app that's gonna make the migration painful

**Comment by doom369** [comment]
Sorry, didn't expect someone uses it.

**Comment by IgnatBeresnev** [comment]
Yeah, I had to roll back to the previous version and the project compiled, woho! :) If after testing batch insert speed we do decide to migrate to your library, that's gonna a problem :(

Maybe we're the only ones using it, who knows :) 

Do you have any alternative to external data maybe? A suggestion of how it could be rewritten using your library?

P.S. I expect the official jdbc driver to be full of such hacks, since clickhouse has very specific things like 'SELECT ... WITH TOTALS', result of which you cannot obtain through jdbc abstraction, you have to break it and call specific methods from specific implementations. I believe people do rely on this.

**Comment by doom369** [comment]
My main motivation was to simplify the code. However, if it used, we can revert. Not big deal.

**Comment by IgnatBeresnev** [comment]
Thanks so much!

**Comment by doom369** [comment]
@IgnatBeresnev released in 1.4.4. Please let me know if it works/not works.
